### ISSUE TITLE
Freeze when closing

### ISSUE THREAD

**Issue by leptun** [vintagepc/MK404#103]
The emulator sometimes freezes when I try to close it with 'q'. It's a random issue. I have to CTRL+C to break the program from the terminal window. The GL window doesn't close.
Latest lines before the freeze:
```
Writing flash state...
avr_special_deinit
Wrote 4096 bytes of EEPROM to Einsy_atmega2560_eeprom.bin
MMU_stop()
AVR finished.
```
I wasn't using the MMU, btw.

**Comment by vintagepc** [comment]
I'm going to close this; I have not seen it recur since I made the GL threading fixes in #188 - Makes sense since it wasn't obviously getting stuck in one of our primary serial or AVR threads. 

Feel free to re-open if it is observed again.
