### ISSUE TITLE
Questions and chit-chat

### ISSUE THREAD

**Issue by leptun** [vintagepc/MK404#12]
Hi @vintagepc 
Thank you for inviting me to this project. I've read what you wrote so far in readme.md. I have a few questions:
How do you propose that we communicate after you push the first usable source code?
Are there others involved in the project?

**Comment by vintagepc** [comment]
We are public! 

Note this decoupled the previous fork(s) you may have had to private repos, so you will need to create a new fork and/or rebase your changes onto the current repo.

**Comment by leptun** [comment]
Wonderful news! Where are you planning to make a post about the project?

**Comment by vintagepc** [comment]
I haven't thought that far ahead, I figure I might just let it gain its own momentum. I might post about it in the PR forums. 

(I don't do social media like reddit etc, so my exposure avenues are somewhat limited). 

Who knows, maybe someday we'll get featured on a Prusa livestream or blog post... :rofl:

**Comment by DRracer** [comment]
@vintagepc great news! I'll talk to our Content team about the (now public) MK3SIM, in fact I already got some questions about its state and whether it will get public one day.
The best timing to promote your huge effort is with FW 3.9.1 and largely repaired Linear Advance 1.5, which wouldn't be possible without the SIM and direct insight into what is going on in the algorithms during printing. @wavexx , what do you think?

**Comment by DRracer** [comment]
@vintagepc - a short notice:
- cloned with submodules
- apt install libelf-dev libsdl-dev freeglut3-dev
- opened CMakeLists.txt in QtCreator 4.13b1
- compiled like a charm with gcc-10.1.0 ;)
It runs, however I'm still having problems with the boot process taking about a minute. The "P" and "E" letters are rotating, but nothing is happening. It is standing at `pBoard->WaitForFinish();` and some other threads are possibly waiting for UART. At least I can debug it nicely with full comfort in QtCreator ;) . I'll let you know if I discover something (if @leptun isn't faster as always :) ).

**Comment by vintagepc** [comment]
> @vintagepc - a short notice:
> 
> * cloned with submodules
> * apt install libelf-dev libsdl-dev freeglut3-dev
> * opened CMakeLists.txt in QtCreator 4.13b1
> * compiled like a charm with gcc-10.1.0 ;)
>   It runs, however I'm still having problems with the boot process taking about a minute. The "P" and "E" letters are rotating, but nothing is happening. It is standing at `pBoard->WaitForFinish();` and some other threads are possibly waiting for UART. At least I can debug it nicely with full comfort in QtCreator ;) . I'll let you know if I discover something (if @leptun isn't faster as always :) ).

Interesting, please feel free to start a separate issue thread so we can debug this without other messages getting interleaved. 

(You did load a firmware to flash at least once with a -f flag or PS/avrdude, right? Otherwise you might just be bootlooping the bootloader.)

The wait state sounds about as expected, WaitForFinish() is basically a thread_join that returns when the AVR shuts down. Most of the other threads are indeed just serial helpers. 

It might be useful in this case to inspect the avr->pc value while it's bootlooping and reference that back to an objdump of the .afx file to see in what function it's stuck.

**Comment by DRracer** [comment]
@vintagepc sorry, my bad, no firmware (parameter -f). Now it runs well, thanks for your hint.

**Comment by vintagepc** [comment]
No worries. I added a note to the README to that extent, you weren't the first, and won't be the last ;)

**Comment by wavexx** [comment]
On Sun, Jul 26 2020, DRracer wrote:
> @wavexx , what do you think?

I think it would be awesome if possible!

**Comment by 3d-gussner** [comment]
https://twitter.com/MarlinFirmware/status/1287259911303442432

**Comment by vintagepc** [comment]
Heh, that explains the giant spike in traffic yesterday 😁

**Comment by vintagepc** [comment]
I've enabled a wiki for the project, seems like a useful addition as a place to document technical info as required. 

Feel free to add/edit as you see fit, hopefully it will morph into something with a clearer direction as we find uses for it. :)

**Comment by vintagepc** [comment]
Welp, I posted about it in the forums. 
Time to brace for the masses :rofl:
