### ISSUE TITLE
Enable test different IR sensor versions

### ISSUE THREAD

**Issue by 3d-gussner** [vintagepc/MK404#122]
Please checkout my https://github.com/3d-gussner/MK3SIM/tree/my_master
With this i can test "old" and "new" MK3s IR sensors
- IR 0.3 or older sensor using toggle 'g'
- IR 0.4 or newer sensor

I don't want to create a PR yet as not that familiar with the MK3SIM

**Comment by vintagepc** [comment]
This'd probably go well after #183

**Comment by vintagepc** [comment]
Added these options to the context menu:

![image](https://user-images.githubusercontent.com/53943260/88489544-cd84d280-cf62-11ea-9b60-11dbac371d23.png)
