### ISSUE TITLE
[FEATURE] Alternate visual options

### ISSUE THREAD

**Issue by vintagepc** [vintagepc/MK404#187]
@gregsaun,expressed interest in alternate (:bear: ) visuals. Probably a feature we'll want to have in order to support other models of printer. 

Start thinking about ways we can do this, maybe a model table with offsets rather than reimplementing the entire MK3SGL class for every model. 

Maybe acquire a set of Bear visuals in order to facilitate this and see what problems come out of the woodwork during the process...

**Comment by gregsaun** [comment]
Thank you for have noted my interested :)

I'll be happy to provide everything I can make to help you. You can already download the Bear 2.1 frame in Fusion 360 and STEP format from here: https://github.com/gregsaun/prusa_i3_bear_upgrade/tree/dev/src . The Bear extruder is available from here (same file formats): https://github.com/gregsaun/bear_extruder_and_x_axis/tree/master/source . Note the Bear frame repo does not contain the extruder because you can use the Prusa extruder on the Bear frame or Prusa frame with the Bear extruder.

**Comment by leptun** [comment]
@vintagepc do you want me to make new OBJ files?

**Comment by gregsaun** [comment]
If you use the STEP file to make OBJ files make sure to remove the "build helpers". There is one for Y axis and one for Z axis:
![build_helper_01](https://user-images.githubusercontent.com/12335098/88653881-edd0a080-d0cc-11ea-88aa-a6e46a2c6284.jpg)
![build_helper_02](https://user-images.githubusercontent.com/12335098/88653878-ed380a00-d0cc-11ea-8cc3-f32345206981.jpg)

If building OBJ files is just an export from an STL (Meshmixer?) I can make those for you, no problem.

**Comment by leptun** [comment]
For the time being I used Solidworks and a plugin to export as that is my main CAD software. I’m doing it like this just so that the output file is consistent.
Also, I had an assembly of the MK3 in Solidworks format and it was easier than using steps. Also, I could split the printer into subassemblies.

**Comment by gregsaun** [comment]
Okay I see. Unfortunately I use Fusion 360 so STEP is probably best if you want to import to Solidworks.

However, I have just checked and Fusion 360 can export an OBJ. It takes a bit of time but I test it and share it here in case it looks to be good.

**Comment by vintagepc** [comment]
Unfortunately we've been there before. Maybe you'll have better luck with a paid version if that's what you're using, but when I tried it with the maker license, the OBJs I got did not export materials, and you could not export multiple objects into one. 

FreeCAD does support MTL exports but the resulting appearance of the export was dissapointing given the number of triangles. There is a discussion on this in #50 with plenty of screenshots; in the end we concluded that Solidworks was the final export tool of choice. 

- You can use "GLC player" to examine the existing OBJs in the assets/ folder to see what I mean - each one contains multiple objects and materials, we've mostly broken them down by sub assemblies to swap them in/out as needed.

**Comment by gregsaun** [comment]
I have the paid license but it looks like the material isn't exported.
![bear_obj_export_test_01](https://user-images.githubusercontent.com/12335098/88660276-b535c480-d0d6-11ea-87b7-b1ca4a42c5b0.jpg)

**Comment by vintagepc** [comment]
Darn - if you look at the 'Model' button on the left panel, are they all distinct components, or is it just one giant mesh? If the former, it may be possible to manually apply materials. But if it's all the same surface that's not possible. :disappointed:

**Comment by gregsaun** [comment]
I have individual components yes. I cna share the OBJ and a prepared STEP file. The step file has the material (at least color).

**Comment by vintagepc** [comment]
That's good - since it's just a text format I could just extract materials from the existing mtl files we have rather than manually migrate the data from the STEP. - the OBJ alone should be enough.

We'll have to see how it goes as a complete assembly, I think it's possible to rework things to handle that. But we might need to split things up into the separate moving components (X, Y, Z) for ease of handling within GL; depends how the object itself is structured. 

We had to split them for the other models because SW joins objects with the same material together - so if you tried to move the extruder, all other black parts would move left and right as well :rofl: (There was also lite mode which saved a lot of file loading overhead by doing that. But there's not much point in a Bear lite mode as it'd look about the same as the regular lite.)

**Comment by gregsaun** [comment]
Looks like he has grouped some stuffs together so not sure how it goes. If you like I can create an OBJ for each axis + frame. If that could make things easier.

**Comment by vintagepc** [comment]
Ah, OK. Lets do that then. 

Here are the assemblies we have for the existing model:
- Extruder, minus the two moving inner fan parts (already have separate objs for those to animate them)
- X axis (Z gantry)
- Y axis (minus steel sheet, already separate obj)
- Frame (minus LCD knob, separate obj already). 

In order to cut down on the triangle count and file size, you can also hide any internal objects that are not visible - for example the internal IR sensor ball, lever mechanism, some screws, the balls, if the LM8UUs have them modeled, etc)

I'm sure we'll find more things as we go along, this is usually an iterative process to get right.

**Comment by gregsaun** [comment]
Awesome, I'll prepare that. What about belts (mine have no teeth)?

**Comment by vintagepc** [comment]
We don't have any for the existing model but if it has no teeth it would look fine just leaving it on in the fixed parent assembly.

**Comment by gregsaun** [comment]
Here it is :)
[bear21_mk3s_simulator.zip](https://github.com/vintagepc/MK404/files/4988499/bear21_mk3s_simulator.zip)

Thanks for all the hard work, very much appreciated.

**Comment by vintagepc** [comment]
Thanks, I'll poke at it a bit after work tonight.

**Comment by vintagepc** [comment]
This is interesting, the objs do have MTL references:

`mtllib d2b749dc-85a2-4cde-b3fc-98cb260eb702.mtl`

...
`usemtl Aluminum_-_Satin`

Do you perhaps need to download or retrieve them separately? I can't imagine they'd go through all the trouble of handling it and not exposing the materials file.

**Comment by 3d-gussner** [comment]
I may have found a way to "export" Fusion 360 to obj + mtl.
1. Disable history
2. Convert Body "BRep to Mesh"
3. Save as OBJ

Result:
<name>.obj + <name>.mtl
[Cubes.zip](https://github.com/vintagepc/MK404/files/4993175/Cubes.zip)

Now have to try an assembly.

**Comment by gregsaun** [comment]
@vintagepc Very happy you like the Bear. Contact me first if you like to build a Bear from scratch ;)

@vintagepc @3d-gussner Oh that is nice, let me redo the export then!

**Comment by 3d-gussner** [comment]
https://apps.autodesk.com/FUSION/en/Detail/Index?id=161925079138285899&appLang=en&os=Win64 Seams to work. Here an example of a Zaribo:
![image](https://user-images.githubusercontent.com/25530011/88784514-6cdadd00-d190-11ea-85b7-aa043a96114b.png)
![image](https://user-images.githubusercontent.com/25530011/88784625-8da33280-d190-11ea-8093-a49436aa666a.png)

**Comment by gregsaun** [comment]
Here are the OBJ, I used the proposed @3d-gussner plugin, it 
[bear21_mk3s_simulator_02.zip](https://github.com/vintagepc/MK404/files/4994669/bear21_mk3s_simulator_02.zip)
seems to work well.

I made a complete assembly OBJ and also separated axis OBJs.

**Comment by 3d-gussner** [comment]
> I made a complete assembly OBJ and also separated axis OBJs.

![image](https://user-images.githubusercontent.com/25530011/88798171-c947f780-d1a4-11ea-9dd3-e394226b61ce.png)
Looks like some components don't have the correct material ;-)

**Comment by gregsaun** [comment]
Yeah I save some time with not setting all the material. I have a print settings and BOM for that ;)

**Comment by vintagepc** [comment]
Let's not get too caught up - the materials are trivial to manipulate, so it's relatively easy to swap one for the other. I can work with what we have, I think, so the time spent trying to get it to export perfectly is probably more than the time for me to just edit the file.  :+1: 

I'm working on the model-swapping framework now, once that's in hopefully it's pretty trivial to add the models and take it from there.

**Comment by gregsaun** [comment]
If I could avoid to change all materials and redoing a exports, pushing to github source files and so on I would appreciate :D . But if this become a too big work I can figure it out. Why is the type of material important? I mean what is important is to have different material, isn't it?

**Comment by vintagepc** [comment]
The mtl files that are paired with the OBJ define how the object renders - that is why the material as a whole matters, not just the name. If you look in the .mtl file with a text editor, then you can see that each material has a set of properties that define things like colour, reflectiveness, etc. and these are used directly to set the appearance of the polygons during the render.

It would have been very nice to be able to export the obj+mtl together and use as-is without extra work, but as it is we'd either need to spend a bunch of time fiddling with the source CAD files to get it to export correctly via some ill-defined pathway, or I can spend an hour or so changing material names in the .obj/mtl file by hand. That only gets unpleasant if models have to be updated regularly.

Results are viewable with GLC_player. so if you'd like to try your hand at it, it is relatively straightforward, if a little tedious:
- Open the .obj file with a good text editor that can handle large files. 
- If changing the .mtl file, edit the `mtllib` line to match the name of the new .mtl file. May or may not be needed depending on what we got from the export, I haven't looked at the new files yet. Materials can be transplanted from one .mtl file to another by copy-pasting their text blocks. 
- Find the `usemtl` command for the body you wish to change, and edit the material name to the new one. 
- Reload the obj in glc_player and observe the changes.
- Repeat. the previous two steps until satisfied. :grin:

**Comment by gregsaun** [comment]
Okay that make sense, in this case I prefer to set properly everything in CAD (I don't like to redo stuffs). However, my parameters might be different than the other Prusa you already have in your simulator (but probably closer).

In Fusion 360 there is the appearance and the physical material. Looks like MTL take only the appearance into account, am I correct?

**Comment by vintagepc** [comment]
Perhaps that is it - unfortunately I cannot say for sure as I haven't dived into the MTL exports from Fusion after our initial failure with the 3S model. We found it just worked from Solidworks so went with that, also since it was the format of the original source we used. 

Should be easy to identify though with a simple test model that has two cubes, one with a material and one with an appearance set, and seeing which one comes out correctly.

It doesn't help that the term "material" is being used in different contexts in the different tools :roll_eyes:

**Comment by gregsaun** [comment]
Okay after more testing it does not seem to have trace of physical material from Fusion 360, it only uses appearance. That makes my job a little easier then. Do you still want separated OBJ for all axis or doing a single one is enough for you now that I know how to set things correctly?

**Comment by vintagepc** [comment]
That's excellent!

I would still prefer separate objects for each axis (essentially, collection of bodies that need to move together, independent of other bodies). It's probably possible to do it with a single OBJ, but I don't think that's very maintainable longer term - it would fall apart pretty quickly if the models changed.

**Comment by vintagepc** [comment]
Lighting weirdness aside, making progress!

![image](https://user-images.githubusercontent.com/53943260/88870122-8f95e180-d1e2-11ea-9e4f-de896bf4d30d.png)

**Comment by gregsaun** [comment]
Hu that is some progress! I should share the OBJ with proper material soon ;)

**Comment by vintagepc** [comment]
I may end up editing the materials slightly at the end, it looks like Fusion only exports a Kd (diffuse) parameter. 
This results in a very muted appearance in the object. For example, the knob and SD card (which also have ambient and specular parameters) vs the display housing:

I'll have to dive into the lighting again to see if that's truly the case since it doesn't render as poorly in GLC player. We'll see. 

![image](https://user-images.githubusercontent.com/53943260/88926261-b89a8e80-d243-11ea-81ad-8551b46baa6d.png)

**Comment by gregsaun** [comment]
Okay let me know if I can help you in a way. I used the plugin maybe I can try again from Fusion 360 directly if you like.

Here is the export: 
[bear21_mk3s_simulator_03.zip](https://github.com/vintagepc/MK404/files/5002396/bear21_mk3s_simulator_03.zip)

I have included a full export in case you need some other parts like the know and fans. Note that the hotend fan in the full assembly has been designed by myself and looks like a Sunon. The LCD knob is a little different but very close. The print fan is also my own model and should be close.

**Comment by gregsaun** [comment]
Wait, it looks like the extrusion does not have the correct rendering. Let me export it again.

**Comment by vintagepc** [comment]
Ah, OK - if you are using different fan models/knobs, then feel free to export those models separately too. The outer "shell" of the fan can remain part of the E assembly, I would just need the rotor as a standalone piece because we spin it if the fan is on.

**Comment by gregsaun** [comment]
Okay I will do that!

**Comment by gregsaun** [comment]
Okay here you have everything:
[bear21_mk3s_simulator_04.zip](https://github.com/vintagepc/MK404/files/5002564/bear21_mk3s_simulator_04.zip)

I have included two version of the extruder, with and without the hotend fan "outer shell". If it is too much work for you go with the fan and knob you already use.

**Comment by vintagepc** [comment]
Great. The added work to swap out the model is minimal, the bulk of it just comes from setting up the positioning relative to the model - and that's also fairly minor. 

The real bear (heh) is the backend framework, but that's not really an impediment, we need it anyway since the intent is that we'll ultimately support completely different printer "models" which may not even look anything like a MK3, so a layer of abstraction between the drawing and the actual model components is a good thing to have. :+1:

**Comment by gregsaun** [comment]
That all sounds very nice, looking forward to test this :)

**Comment by vintagepc** [comment]
Whoops- looks like you left the print fan shroud hidden by accident in the E export.

**Comment by gregsaun** [comment]
This is normal, the shroud is completely different than the Prusa one.

**Comment by vintagepc** [comment]
Sorry, maybe I'm misunderstanding - I'm referring to the outer housing of the part cooling fan, the 5150 blower. 

The hot-end cooling fan shroud is present and accounted for :+1:

Getting close, I now just need to fix the lighting and un-break all the things I broke in the "standard" 3d models 😁

**Comment by gregsaun** [comment]
Ha sorry, you can reuse the complete print fan you have for Original Prusa for that :). Looking forward to see it!

**Comment by vintagepc** [comment]
Getting closer, I think I've sorted the lighting. 

![image](https://user-images.githubusercontent.com/53943260/89090320-2d6ae700-d370-11ea-96b0-ec88b88f0c56.png)

The motors looking weird is a WIP, I've filed a bug/info request with https://github.com/tinyobjloader/tinyobjloader/issues/279

Part fan shroud is still missing, I need to extract the model from the 3S extruder first. 

Hopefully I can wrap this up tomorrow!

**Comment by gregsaun** [comment]
It start to look good! I was wondering how the motors would render due to the material set on faces...

Do you want the print fan shroud without the blades? Mine is one piece normally and has no blade but I can try to remove them for you if you like.

Quick question, I saw you are using a different color for the LCD screen, is there a reason for that? I am asking because I have made an Inkscape SVG project for writing the menu in my assembly guides so it would be nice to use the simulator for that. Just a nice to have, nothing urgent or mandatory ;)

**Comment by vintagepc** [comment]
That particular color combo is easier to read in the 3d graphics. the 2D display/control panel view is blue and white by default:

![image](https://user-images.githubusercontent.com/53943260/89102595-f977dc00-d3d8-11ea-8032-5bf3c1d01617.png)

Also, I'm partial because that's what my real display looks like... :grin: 

![image](https://user-images.githubusercontent.com/53943260/89102568-a3a33400-d3d8-11ea-984f-741f48e13082.png)

**Comment by gregsaun** [comment]
Ok I see, hard to read I agree. I was suspecting you did upgrade the real LCD screen haha :D

**Comment by vintagepc** [comment]
If you can easily export the shroud sans the center blade, that would save me some time - thanks.

**Comment by gregsaun** [comment]
I'll do it now

**Comment by vintagepc** [comment]
I posted a guide on the display mod here:
https://forum.prusaprinters.org/forum/original-prusa-i3-mk3s-mk3-user-mods-octoprint-enclosures-nozzles-.../a-very-much-needed-improvement/

It's not an off-the shelf part or LCD module.

**Comment by gregsaun** [comment]
Oh that was you, nice!

**Comment by gregsaun** [comment]
I know I have seen your nickname few times :D

Here is the print fan: 
[bear21_mk3s_simulator_print_fan.zip](https://github.com/vintagepc/MK404/files/5010518/bear21_mk3s_simulator_print_fan.zip)

**Comment by vintagepc** [comment]
It is dangerous to be a man of many skills and with far too much free time... :rofl: 

Thanks, will get that shroud in at some point.

**Comment by gregsaun** [comment]
Oh yeah I know very well what you mean hahaha

**Comment by vintagepc** [comment]
I think I've got all the issues ironed out, though I turned the per-face material issue into a separate bug.
`./MK404 -g bear`

**Comment by gregsaun** [comment]
Thank you very much!

I tried to launch your latest release and I get this error:
```
$ ./MK404 -h
./MK404: error while loading shared libraries: libGLEW.so.2.0: cannot open shared object file: No such file or directory
```

I have compiled master branch and I can launch it. To compile it successfully I had to add few libraries including the one linked in the error message. However, I have a "printer not found" message on the LCD emulator window.

For information, I am on a VM through virtualbox with fresh Ubuntu installation (minimal).

**Comment by vintagepc** [comment]
hmm... what glew version does the system have? I'm using 2.1.0

**Comment by gregsaun** [comment]
I have 2.1.0 as well. The symbolic links worked: `ln -s /usr/lib/x86_64-linux-gnu/libGLEW.so.2.1.0 /usr/lib/libGLEW.so.2.0` .

**Comment by vintagepc** [comment]
awesome! :tada:

**Comment by vintagepc** [comment]
Just an FYI @gregsaun - no affiliation/association with Marlin (re your tweet). We were just fortunate to get featured because we'd invited one of the Marlin devs as an early beta tester. :+1:

**Comment by gregsaun** [comment]
I was thinking that I was wrong so thanks for clarification, will add a note to the tweet. 👍
