### ISSUE TITLE
[BUG] Broken graphics

### ISSUE THREAD

**Issue by leptun** [vintagepc/MK404#218]
**Describe the bug**
The graphics seem to be broken in the latest master branch. I'm using Prusa_MK3SMMU2 fancy graphics.
Stuff that I can see is broken:
- The bed LED is floating mid-air, but it's working
- One of the MMU motors seems to blink with green graphics on startup sometimes
- The extruder visualizer is turning much too little.

**To Reproduce**
`./MK404 -s Prusa_MK3SMMU2 -g fancy -m`

**Expected behavior**
It should work :)

**Screenshots**
![image](https://user-images.githubusercontent.com/17808203/89776014-b375f300-db11-11ea-8a87-eecb49876ece.png)
![image](https://user-images.githubusercontent.com/17808203/89776147-f932bb80-db11-11ea-9bef-c90131b82088.png)

**Desktop (please complete the following information):**
Ubuntu 18.04.4 LTS - VMware

**Comment by vintagepc** [comment]
whoops! probably some side effects from the Bear visuals rework.

**Comment by leptun** [comment]
Also, just noticed this as well: The backlight is stuck on 100% brightness

**Comment by vintagepc** [comment]
oh, good. I thought I broke that during my cleanup in #217 ... was scratching my head why.

**Comment by vintagepc** [comment]
I didn't think the MK3 OBJ files had any per-face colours, but what probably happened is #190 changed the indexing for the objects we show and hide.

**Comment by vintagepc** [comment]
Just noticed we're also no longer showing the correct E variant (MMU/std)

**Comment by vintagepc** [comment]
Looks like the brightness was broken by https://github.com/vintagepc/simavr/commit/e838af1472e8402f4260e6432cbbe6d6a6fe6a85

Investigating...
