### ISSUE TITLE
[BUG] Serial is broken

### ISSUE THREAD

**Issue by leptun** [vintagepc/MK404#234]
In the latest master branch you can't use the -s option anymore. It starts the /dev/pts/2|3 as usual, but the /tmp/simavr-uart* symlink is incorrect.
Differences I noticed: Instead of simavr-uart0|2, you get simavr-uart48|50. These symlinks also are not deleted after the ports are closed. Reverting to v0.9.3 fixed the issue.

**Comment by vintagepc** [comment]
crap, I'll take a look after work.

**Comment by vintagepc** [comment]
There was a malformed link name. Looking at the code, it's never cleaned it up after quitting. 

Fixing the symlink name appears to have fixed the communication, I can connect to /tmp/simavr-uart0 without issue.
