### ISSUE TITLE
[FEATURE] Make the filament loaded on startup

### ISSUE THREAD

**Issue by leptun** [vintagepc/MK404#239]
**Is your feature request related to a problem? Please describe.**
I always forget to load the filament on startup before starting a test print and more often than not I end up doing a filament swap at the beginning of the print. 

**Describe the solution you'd like**
Please make the filament to be loaded on startup or add an extra flag for that.

**Comment by vintagepc** [comment]
Can definitely do that.

**Comment by leptun** [comment]
@vintagepc Thanks!

**Comment by vintagepc** [comment]
You're welcome... it's bitten me a few time before too but I just never got around to doing something about it... ;-)
