### ISSUE TITLE
[BUG] Prusa_MK25 and Prusa_MK25S bed temp rises without any reason

### ISSUE THREAD

**Issue by 3d-gussner** [vintagepc/MK404#252]
**Describe the bug**
After starting the MK25 or MK25S the bed temp starts rising without any reason.

**To Reproduce**
1. start./ MK404 Prusa_MK25_mR13 -f (3.9.1 hex file)
2. Watch the Bed temp on LCD
3. Starting the base model MK2 doesn't do that. 

**Expected behavior**
Behave like the base MK2 or MK3/s 

**Desktop (please complete the following information):**
 - OS: [Ubuntu VM]
 - Version [18.04]

**Additional context**
Tried to find the issue but can't find it.
Did `git reset --hard` and rebuild everything.

**Comment by vintagepc** [comment]
This is the soft PWM bed code causing this. looks like the 2.5 variants need the bIsBed argument set to true to indicate we're doing softPWM trickery.
