### ISSUE TITLE
[BUG] MK2 PINDA doesn't trigger

### ISSUE THREAD

**Issue by 3d-gussner** [vintagepc/MK404#253]
**Describe the bug**
Started Prusa_MK2 with latest official firmware and tried to run the wizard, but i fails in the selftest at z.
Tried G28W to home and the PINDA doesn't trigger.

**To Reproduce**
1. Start ./MK404 Prusa_MK2_mR13 -s -f (MK2 hex file)
2. Run selftest or `G28W`
3. Selftest fails and PINDA doesn't trigger

**Expected behavior**
Should trigger above the MK42 cal points.

**Desktop (please complete the following information):**
 - OS: [Ubuntu VM]
 - Version [18.04]

**Additional context**
Saw that you added the MK42 cal points but looks like it doesn't work.

**Comment by vintagepc** [comment]
Interesting; I know I had the self test completing at one point. I wonder what changed...

**Comment by vintagepc** [comment]
This is a weird one,  the microstep count (and therefore position tracking) doesn't seem to be working right. 

I can see the firmware is setting the driver MS1/2 to H/H (MS 16), correct according to the source.

But when I try a move axis/step, it's only stepping about 1/16th of what it should. Are the MS outputs inverted? Doesn't look that way on the schematic.

**Comment by vintagepc** [comment]
Any chance @wavexx  or @leptun has some insight on the miniRambo line with regards to this? From what I can see it looks like the FW is stepping as though it's in full-step mode but the driver is configured for 16ths. 

Steps/mm should be configured correctly as well.

**Comment by wavexx** [comment]
No direct experience with the miniRambo
