### ISSUE TITLE
[BUG] MBL map does not appear to work for print simulation

### ISSUE THREAD

**Issue by vintagepc** [vintagepc/MK404#266]
**Describe the bug**

Per the discussion on #264, it looks like the printer MBL map isn't working right. Investigate.

**Comment by DRracer** [comment]
Update - the white print line follows the bed (had to make a really bad heatbed with 1.5mm peaks), but the highres extrusion visualization doesn't (this lays flat onto the bed).

**Comment by DRracer** [comment]
Screenshot from the sim:
![MBL_issues](https://user-images.githubusercontent.com/26795080/95580832-452dae00-0a38-11eb-8500-98b010af13ce.png)
notice the white line going up on the right side

**Comment by vintagepc** [comment]
Ah, this may just be a simple oversight. It looks like AddSegment() uses the same Z start/end values for the extrusion chunk.

**Comment by 3d-gussner** [comment]
> Update - the white print line follows the bed (had to make a really bad heatbed with 1.5mm peaks), but the highres extrusion visualization doesn't (this lays flat onto the bed).

You should contact Support if you have that kind of bent bed 😁 and ask for replacement

**Comment by vintagepc** [comment]
Sounds like the complaint is "my bed isn't broken enough, it prints too level!" to me :rofl:

**Comment by DRracer** [comment]
@vintagepc I'm afraid this may get a little more complicated, because we need to take the Z-motor nonlinearity into consideration while processing the printed segment

**Comment by vintagepc** [comment]
And the backlog gets longer.... :stuck_out_tongue: 

Are we thinking part of the cause of 602 is non-linearity coupled with MBL?

**Comment by vintagepc** [comment]
I pushed up a print-sim-enhancements branch which has a partial for what I bashed out this morning. 

It brings a dT (delta cpu cycles) through to OnEStep and fixes the Z endpoint of print segments. Didn't have time to check it though so it might be horribly broken.

**Comment by DRracer** [comment]
Nope, issue 602 is purely caused by nonlinearity of the E-motor.
But for the sake of completness, Z-axis and MBL related issues (line segmentation) are missing in our analysis so far.

Delta CPU cycles: that should be enough, I'll look into it.

**Comment by vintagepc** [comment]
I'm hoping just fixing the segment start/end Z might actually be enough to make issues visible given the x/y segment sizes tend to be very small in HR modes anyway. But if not we can improve the calculations. 

I suspect it might be necessary to carry the deltaT down through to the addSegment function, but I'm not 100% sure. It might be perfectly satisfactory to calculate an adjusted E value based on that during the main onEStep calculations as well.

**Comment by vintagepc** [comment]
OK - can confirm that the simulated print now follows the MBL curve as expected:

![image](https://user-images.githubusercontent.com/53943260/95666040-e180af00-0b23-11eb-874e-83f9643c87ab.png)

Z nonlinearity can be enabled and with the quads being so small I expect that it should reveal any issues as a gap between adjacent ones as opposed to a smooth transition. 

Is there anything else do do on this particular issue or is this satisfactory for now?
