### ISSUE TITLE
[BUG] Crash on LCD desync

### ISSUE THREAD

**Issue by wavexx** [vintagepc/MK404#362]
**Describe the bug**
Using LCD->Desync can cause the following assertion failure:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  array::at: __n (which is 124) >= _Nm (which is 104)
```

**To Reproduce**
1. Emulate any MK3 FW
2. Middle click -> LCD -> Desync
3. Wait about 2 seconds
4. Repeat from step 2 if crash doesn't happen

**Expected behavior**
No ouch on the cli ;)

**Desktop (please complete the following information):**
 - OS: linux debian/unstable

**Comment by vintagepc** [comment]
Heh, the desync probably results in the display receiving an address directive that is off the end of the memory array. Hopefully an easy fix
